### ISSUE TITLE
Problem with Bootstrap-sprockets

### ISSUE THREAD

**Issue by scallyw4g** [bricesanchez/spree-refinery-authentication#11]
Getting an error after installing as per instructions in readme.  

```
 Sprockets::FileNotFound in Spree::Home#index 

couldn't find file 'bootstrap-sprockets' with type 'application/javascript'

/home/scallywag/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/spree-2f7322cdd764/frontend/app/assets/javascripts/spree/frontend.js:1
sprockets (3.4.0) lib/sprockets/resolve.rb:64:in `resolve!'
sprockets (3.4.0) lib/sprockets/directive_processor.rb:399:in `resolve'
sprockets (3.4.0) lib/sprockets/directive_processor.rb:207:in `process_require_directive'
sprockets (3.4.0) lib/sprockets/directive_processor.rb:180:in `block in process_directives'
sprockets (3.4.0) lib/sprockets/directive_processor.rb:178:in `each'
sprockets (3.4.0) lib/sprockets/directive_processor.rb:178:in `process_directives'
sprockets (3.4.0) lib/sprockets/directive_processor.rb:83:in `_call'
sprockets (3.4.0) lib/sprockets/directive_processor.rb:68:in `call'
sprockets (3.4.0) lib/sprockets/processor_utils.rb:75:in `call_processor'
sprockets (3.4.0) lib/sprockets/processor_utils.rb:57:in `block in call_processors'
sprockets (3.4.0) lib/sprockets/processor_utils.rb:56:in `reverse_each'
sprockets (3.4.0) lib/sprockets/processor_utils.rb:56:in `call_processors'
sprockets (3.4.0) lib/sprockets/loader.rb:134:in `load_from_unloaded'
sprockets (3.4.0) lib/sprockets/loader.rb:60:in `block in load'
sprockets (3.4.0) lib/sprockets/loader.rb:318:in `fetch_asset_from_dependency_cache'
sprockets (3.4.0) lib/sprockets/loader.rb:44:in `load'
sprockets (3.4.0) lib/sprockets/cached_environment.rb:20:in `block in initialize'
sprockets (3.4.0) lib/sprockets/cached_environment.rb:47:in `yield'
sprockets (3.4.0) lib/sprockets/cached_environment.rb:47:in `load'
sprockets (3.4.0) lib/sprockets/bundle.rb:23:in `block in call'
```

Steps to reproduce on Rails 4.2.4: 

``` bash
rails new spreefiner
cd spreefinery
```

add to Gemfile:

```
gem 'refinerycms', github: 'refinery/refinerycms', branch: 'master'
gem 'quiet_assets', :group => :development

# Add support for searching inside Refinery's admin interface.
gem 'refinerycms-acts-as-indexed', ['~> 2.0', '>= 2.0.0']

# Add support for Refinery's custom fork of the visual editor WYMeditor.
gem 'refinerycms-wymeditor', ['~> 1.0', '>= 1.0.6']

gem 'spree', github: 'spree/spree', branch: '3-0-stable'
gem 'spree_auth_devise', github: 'spree/spree_auth_devise', branch: '3-0-stable'
gem 'spree-refinerycms-authentication', github: 'bricesanchez/spree-refinery-authentication', branch: '3-0-stable'
```

``` bash
bundle install
rails g spree:install
```

Change spree user_class in initializer to

```
Spree.user_class = "Spree::User"
```

Add Routes

```
root :to => "refinery/pages#home"
mount Spree::Core::Engine, :at => '/shop'
mount Refinery::Core::Engine, at: '/'
```

And 

```
rails s
```

Interestingly, this does not happen when running the generator before the spree-refinerycms-authentication gem has been added.

**Comment by bricesanchez** [comment]
Is your error could be related to this : https://github.com/refinery/refinerycms/issues/3148 ?
